# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: "local"
  hooks:
  - id: "mktopics"
    name: "Run ./mktopics.bash"
    entry: "./mktopics.bash --vcs-aware"
    language: "system"
    pass_filenames: false