# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: "local"
  hooks:
  - id: "problemsets"
    name: "Run ./problemsets.bash"
    entry: "./problemsets.bash --vcs-aware"
    language: "system"
    pass_filenames: false